name: tsa_firebase_auth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: 4.6.5
  firebase_core: 2.1.1
  firebase_auth: 4.0.2
  google_sign_in: 5.4.2
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  platform: ^3.1.0
  geolocator: ^9.0.2
  android_intent_plus: ^3.1.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: CustomIconData
      fonts:
        - asset: assets/fonts/CustomIconData.ttf

